version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    hostname: app
    networks:
      - node-app
    volumes:
      - ./node:/usr/src/app
    tty: true
    expose:
      - 3000
    entrypoint: ./docker-entrypoint.sh

  nginx:
    build:
      context: nginx
    container_name: nginx
    hostname: nginx
    ports:
        - "8080:80" 
    depends_on:
        - app
    networks:
        - node-app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    expose:
      - 3306
    volumes:
      - ./mysql/docker_volume:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-app

networks:
  node-app:
    driver: bridge